import type { ConfigObject } from '@eslint/core';
export declare const config: ConfigObject[];
export declare const configWebApp: ConfigObject[];
export { default as cspellFlagWords } from './lists/cspell.flagWords.js';
export { default as cspellWords } from './lists/cspell.words.js';
export { httpStatusCodes as noMagicNumbersHttpStatusCodes, default as noMagicNumbersIgnore } from './lists/noMagicNumbers.ignore.js';
export { default as writeGoodCommentsWhitelist } from './lists/writeGoodComments.whitelist.js';
export type { ConfigObject } from '@eslint/core';
export { defineConfig } from 'eslint/config';
export default config;
