export const words = [
    'cityssm',
    'saultstemarie',
    'datetimepicker',
    'fieldsets',
    'fontawesome',
    'fullwidth',
    'hoverable',
    'inputmode',
    'noopener',
    'noreferrer',
    'maxlength',
    'onremoved',
    'onshown',
    'trash',
    'vcentered',
    'yellow',
    'autoincrement',
    'ifnull',
    'nvarchar',
    'recordset',
    'httponly',
    'sonarjs',
    'tseslint',
    'millis'
];
export default words;
