name: Test ESLint Config

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]

    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Package
        run: npm ci

      - name: Install ESLint
        run: npm install -g eslint@9.x

      - name: Run Test
        run: npm test
